PREFIX schema: <http://schema.org/>
prefix cds: <http://localhost:8000/data/defs/court-data-definitions.jsonld#> 

SELECT DISTINCT ?ch ?o ?p WHERE {
  ?ch ?o ?p.
  {
    SELECT ?ch WHERE {
      ?ch schema:location ?loc.
      ?loc schema:address ?addr.
      ?addr schema:addressRegion ?state.
      FILTER(?state IN("IL", "CA"))
    }
  }
}