PREFIX schema: <http://schema.org/>
prefix cds: <http://localhost:8000/data/defs/court-data-definitions.jsonld#> 

CONSTRUCT {
  # retrieve all triples under courthouse
  ?ch ?o ?p.
  # contactPoint / areaServed
  ?co ?cpp ?cpo. ?aa ?aap ?aao.
  # address
  ?addr ?addrProp ?addrValue.
  # location
  ?loc ?lop ?loo.
  # openingHoursSpecification
  ?sp ?spp ?spo.
  # areaServed
  ?area ?aop ?aoo.
  # hasOfferCatalog  
  ?hoc ?hop ?hoo.
} 
	WHERE {
      # all subjects ch must be Courthouse
      # ?ch a cds:Courthouse.      
      ?ch ?o ?p; schema:location ?loc.
  	  ?loc ?lop ?loo; schema:address ?addr.      
      ?addr ?addrProp ?addrValue ; schema:addressRegion ?state.
      FILTER(?state IN("CA"))
      OPTIONAL {?ch schema:hasOfferCatalog ?hoc. ?hoc ?hop ?hoo. }
      OPTIONAL {?ch schema:contactPoint ?co. ?co ?cpp ?cpo.}
  	  OPTIONAL {?ch schema:areaServed ?aa. ?aa ?aap ?aao.}
      OPTIONAL {?loc schema:openingHoursSpecification ?sp. ?sp ?spp ?spo.}            
      OPTIONAL {?ch schema:areaServed ?area. ?area ?aop ?aoo.}
    }
